services:
    amf_console.console_application.form:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - "AMF\ConsoleBundle\Form\Type\ConsoleApplicationFormType"
            - ~
            - { validation_groups:["ConsoleApplication"] }
            
    amf_console.console_application.form.type:
        class: AMF\ConsoleBundle\Form\Type\ConsoleApplicationFormType
        tags:
            - { name: form.type }
            
    amf_console.command.form:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - "AMF\ConsoleBundle\Form\Type\CommandFormType"
            - ~
            - { validation_groups:["Command"] }

    amf_console.argument.form:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - "AMF\ConsoleBundle\Form\Type\ArgumentFormType"

    amf_console.console_application.form_handler:
        class: AMF\ConsoleBundle\Form\Handler\ConsoleApplicationFormHandler
        arguments: ["@amf_console.console_application.form", "@kernel"]