AMF\ConsoleBundle\Form\Model\ConsoleApplication:
    properties:
        commands:
            - Valid: ~
            
AMF\ConsoleBundle\Form\Model\Command:
    properties:
        definition:
            - NotBlank: { groups: ['ConsoleApplication'], message: 'error.command.empty' }
            - AMF\ConsoleBundle\Validator\Constraints\AllowedCommand: { message: 'error.command.valid', groups: ['ConsoleApplication'] }
            