cache:
    paths:
        - vendor

before_script:
    # Install composer dependencies
    - curl --silent --show-error https://getcomposer.org/installer | php
    - php composer.phar install
    
test:app:
    script:
        - phpunit --coverage-text --colors=never