services:
    ftven_console.console_application.form:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - "Ftven\ConsoleBundle\Form\Type\ConsoleApplicationFormType"
            - ~
            - { validation_groups:["ConsoleApplication"] }
            
    ftven_console.console_application.form.type:
        class: Ftven\ConsoleBundle\Form\Type\ConsoleApplicationFormType
        tags:
            - { name: form.type }
            
    ftven_console.command.form:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - "Ftven\ConsoleBundle\Form\Type\CommandFormType"
            - ~
            - { validation_groups:["Command"] }

    ftven_console.argument.form:
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", create]
        arguments:
            - "Ftven\ConsoleBundle\Form\Type\ArgumentFormType"

    ftven_console.console_application.form_handler:
        class: Ftven\ConsoleBundle\Form\Handler\ConsoleApplicationFormHandler
        arguments: ["@ftven_console.console_application.form", "@kernel"]